import React from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'

const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
}
const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { duration: 0.55, ease: [0.22, 1, 0.36, 1] } },
}

const INPUTS = [
  { label: 'Daily Screen Time', desc: 'Total hours the screen is active per day (0–12h)', color: '#b880ff' },
  { label: 'Phone Unlocks', desc: 'Number of times you unlock your device daily', color: '#ff6b8a' },
  { label: 'Social Media Usage', desc: 'Time spent on social platforms daily (0–8h)', color: '#3da3ff' },
  { label: 'Night-time Usage', desc: 'Whether you use your device after midnight', color: '#4dc48a' },
  { label: 'Sleep Hours', desc: 'Total sleep duration per night (0–10h)', color: '#ffb81c' },
]

export default function About() {
  return (
    <main className="pt-24 pb-24 px-4">
      <div className="max-w-2xl mx-auto">
        <motion.div
          variants={container}
          initial="hidden"
          animate="show"
          className="space-y-8"
        >
          {/* Header */}
          <motion.div variants={item} className="text-center">
            <h1 className="font-display text-4xl font-medium" style={{ color: '#3d3450' }}>
              About Addiction Lens
            </h1>
            <p className="mt-4 text-sm leading-relaxed" style={{ color: '#7a6e8f' }}>
              A machine-learning based tool for understanding smartphone usage patterns
              and their relationship to addictive behaviour.
            </p>
          </motion.div>

          {/* What it does */}
          <motion.div variants={item} className="glass-card p-7">
            <h2 className="font-display text-xl font-medium mb-3" style={{ color: '#3d3450' }}>
              What does it do?
            </h2>
            <p className="text-sm leading-relaxed" style={{ color: '#6b5f80' }}>
              Addiction Lens uses a pre-trained classification model to analyse five
              behavioural metrics and predict whether your smartphone usage falls into
              a <strong>Low</strong>, <strong>Moderate</strong>, or <strong>High</strong> addiction
              category. Based on your result, the system generates a tailored set of
              recommendations designed to help you develop healthier digital habits.
            </p>
          </motion.div>

          {/* Input features */}
          <motion.div variants={item} className="glass-card p-7">
            <h2 className="font-display text-xl font-medium mb-5" style={{ color: '#3d3450' }}>
              Input features used
            </h2>
            <div className="space-y-4">
              {INPUTS.map(({ label, desc, color }) => (
                <div key={label} className="flex items-start gap-4">
                  <div
                    className="mt-0.5 h-2 w-2 flex-shrink-0 rounded-full"
                    style={{ background: color, marginTop: 6 }}
                  />
                  <div>
                    <p className="text-sm font-medium" style={{ color: '#3d3450' }}>{label}</p>
                    <p className="text-xs" style={{ color: '#8b7ca8' }}>{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Disclaimer */}
          <motion.div
            variants={item}
            className="rounded-2xl p-5"
            style={{
              background: 'rgba(255, 184, 28, 0.06)',
              border: '1px solid rgba(255, 184, 28, 0.2)',
            }}
          >
            <p className="text-xs font-medium uppercase tracking-widest mb-2" style={{ color: '#d4920a' }}>
              Important Disclaimer
            </p>
            <p className="text-sm leading-relaxed" style={{ color: '#6b5f80' }}>
              Addiction Lens is intended for informational and educational purposes only.
              Results are generated by a machine learning model and do not constitute
              a clinical diagnosis. If you are concerned about your smartphone usage or
              its effect on your wellbeing, please consult a qualified healthcare professional.
            </p>
          </motion.div>

          {/* CTA */}
          <motion.div variants={item} className="text-center pt-2">
            <Link
              to="/analyse"
              className="inline-flex items-center gap-2 rounded-2xl px-8 py-3.5 text-sm font-medium text-white transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg btn-shimmer"
              style={{
                background: 'linear-gradient(135deg, #b880ff 0%, #9b4dff 100%)',
                boxShadow: '0 6px 20px rgba(155, 77, 255, 0.25)',
                textDecoration: 'none',
              }}
            >
              Start the Analysis
            </Link>
          </motion.div>
        </motion.div>
      </div>
    </main>
  )
}
