/**
 * Generates and downloads a PDF report using jsPDF.
 * All rendering is client-side — no server required.
 */
export async function downloadReport({ inputs, prediction, recommendations }) {
  // Dynamically import jsPDF to keep initial bundle lean
  const { jsPDF } = await import('jspdf')

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const margin = 48
  let y = margin

  // ── Palette ───────────────────────────────────────
  const COLORS = {
    title: [61, 52, 80],
    accent: [155, 77, 255],
    muted: [139, 124, 168],
    body: [107, 95, 128],
    Low: [39, 168, 108],
    Moderate: [212, 146, 10],
    High: [224, 58, 106],
  }
  const levelColor = COLORS[prediction] ?? COLORS.accent

  // ── Header bar ────────────────────────────────────
  doc.setFillColor(...levelColor)
  doc.rect(0, 0, W, 6, 'F')

  y += 16

  // ── Logo / brand ──────────────────────────────────
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.title)
  doc.text('Addiction Lens', margin, y)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.muted)
  doc.text('Smartphone Behavioural Analysis Report', margin, y + 18)

  const date = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  })
  doc.text(`Generated: ${date}`, W - margin, y + 18, { align: 'right' })

  y += 44

  // ── Divider ───────────────────────────────────────
  doc.setDrawColor(220, 210, 240)
  doc.setLineWidth(0.75)
  doc.line(margin, y, W - margin, y)
  y += 24

  // ── Prediction result ─────────────────────────────
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.muted)
  doc.text('PREDICTED ADDICTION LEVEL', margin, y)
  y += 16

  doc.setFontSize(30)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...levelColor)
  doc.text(prediction, margin, y)
  y += 36

  // ── Input summary section ─────────────────────────
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.title)
  doc.text('Usage Inputs', margin, y)
  y += 16

  const rows = [
    ['Daily Screen Time', `${inputs.screen_time} hours`],
    ['Phone Unlocks per Day', `${inputs.unlocks} times`],
    ['Social Media Usage', `${inputs.social_media} hours`],
    ['Night-time Usage', inputs.night_usage === 1 ? 'Yes' : 'No'],
    ['Sleep Hours', `${inputs.sleep_hours} hours`],
  ]

  doc.setFontSize(10)
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.body)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...COLORS.title)
    doc.text(value, W - margin, y, { align: 'right' })
    y += 22
  })

  y += 12

  // ── Divider ───────────────────────────────────────
  doc.setDrawColor(220, 210, 240)
  doc.line(margin, y, W - margin, y)
  y += 24

  // ── Recommendations ───────────────────────────────
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.title)
  doc.text('Personalised Recommendations', margin, y)
  y += 16

  recommendations.forEach((rec, idx) => {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...levelColor)
    doc.text(`${idx + 1}. ${rec.title}`, margin, y)
    y += 14

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.body)
    const lines = doc.splitTextToSize(rec.body, W - margin * 2)
    doc.text(lines, margin + 12, y)
    y += lines.length * 13 + 8
  })

  y += 16

  // ── Footer ────────────────────────────────────────
  doc.setDrawColor(220, 210, 240)
  doc.line(margin, y, W - margin, y)
  y += 14

  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(...COLORS.muted)
  doc.text(
    'This report is generated by an AI model for informational purposes only and is not a clinical diagnosis.',
    margin,
    y
  )

  doc.save(`addiction-lens-report-${Date.now()}.pdf`)
}
